# Dockerfile for GoReleaser dockers_v2
# GoReleaser organizes binaries by platform: linux/amd64/kubemirror, linux/arm64/kubemirror
FROM gcr.io/distroless/static:nonroot
ARG TARGETPLATFORM
WORKDIR /
COPY ${TARGETPLATFORM}/kubemirror /kubemirror
USER 65532:65532
ENTRYPOINT ["/kubemirror"]
