---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubemirror-controller
  namespace: kubemirror-system
  labels:
    app.kubernetes.io/name: kubemirror
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubemirror
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      scrapeTimeout: 10s
      relabelings:
        # Add namespace label
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        # Add pod label
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        # Add service label
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
